FarisTours/ui/urls.py
from django.urls import path
from . import views
from ui.views import CreateCheckoutSessionView

app_name = "ui"



urlpatterns = [
    path('',views.home,name="home"),
    path('tours',views.tours,name="tours"),
    path('stripe/webhooks',views.stripe_webhook,name="stripe_webhook"),
    path('success/',views.success,name="success"),
    path('cancel/',views.canceled,name="cancel"),
    path('create-checkout-session/<slug:slug>',views.CreateCheckoutSessionView,name="create-checkout-session"),
    path('tour/<slug:slug>',views.tour,name="tour"),
]

FarisTours/templates/client/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US" dir="ltr">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- ===============================================-->
    <!--    Document Title-->
    <!-- ===============================================-->
    <title>{% block title %}{% endblock title %}</title>


    <!-- ===============================================-->
    <!--    Favicons-->
    <!-- ===============================================-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'client/assets/img/favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'client/assets/img/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'client/assets/img/favicons/favicon-16x16.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'client/assets/img/favicons/favicon.ico' %}">
    <link rel="manifest" href="{% static 'client/assets/img/favicons/manifest.json' %}">
    <meta name="msapplication-TileImage" content="{% static 'client/assets/img/favicons/mstile-150x150.png' %}">
    <meta name="theme-color" content="#ffffff">


    <!-- ===============================================-->
    <!--    Stylesheets-->
    <!-- ===============================================-->
    <link href="{% static 'client/assets/css/theme.css' %}" rel="stylesheet" />
{% block head %}


{% endblock head %}
  </head>


  <body>

    <!-- ===============================================-->
    <!--    Main Content-->
    <!-- ===============================================-->
    <main class="main" id="top">
      <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3 d-block" data-navbar-on-scroll="data-navbar-on-scroll">
        <div class="container"><a class="navbar-brand" href="index.html"><img class="d-inline-block" src="{% static 'client/assets/img/gallery/logo.png' %}" width="50" alt="logo" /><span class="fw-bold text-primary ms-2">FarisTours</span></a>
          <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse border-top border-lg-0 mt-4 mt-lg-0" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto pt-2 pt-lg-0 font-base">
              <li class="nav-item px-2"><a class="nav-link fw-medium active" aria-current="page" href="#destinations"><span class="nav-link-icon text-800 fas fa-map-marker-alt"></span><span class="nav-link-text">Locations </span></a></li>
              <li class="nav-item px-2"><a class="nav-link" href="#flights"> <span class="nav-link-icon text-800 fas fa-plane"></span><span class="nav-link-text">Flights</span></a></li>
              <li class="nav-item px-2"><a class="nav-link" href="#hotels"> <span class="nav-link-icon text-800 fas fa-hotel"></span><span class="nav-link-text">Hotels</span></a></li>
              <li class="nav-item px-2"><a class="nav-link" href="#activities"><span class="nav-link-icon text-800 fas fa-bolt"></span><span class="nav-link-text">Activities</span></a></li>
            </ul>
            <form>
              <button class="btn text-800 order-1 order-lg-0 me-2" type="button">Support</button>
              <button class="btn btn-voyage-outline order-0" type="submit"><span class="text-primary">Sign in</span></button>
            </form>
          </div>
        </div>
      </nav>
{% block content %}



{% endblock content %}
    </main>
    <!-- ===============================================-->
    <!--    End of Main Content-->
    <!-- ===============================================-->




    <!-- ===============================================-->
    <!--    JavaScripts-->
    <!-- ===============================================-->
    <script src="{% static 'client/vendors/@popperjs/popper.min.js' %}"></script>
    <script src="{% static 'client/vendors/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'client/vendors/is/is.min.js' %}"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
    <script src="{% static 'client/vendors/fontawesome/all.min.js' %}"></script>
    <script src="{% static 'client/assets/js/theme.js' %}"></script>

    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:wght@300;400;600;700&amp;display=swap" rel="stylesheet">
  {% block scripts %}

{% endblock scripts %}
  </body>

</html>

FarisTours/templates/client/other.html
               <form method="post" id="booking_form" class="ps-form--search" name="booking_form">
                  {% csrf_token %}
                  <div class="form-group">
                  <div class="ps-product__block ps-product__style">
                      <h4>CHOOSE A DATE</h4>
                    </div>
                     <select id="planning" class="form-control">
                        <option value="">Select</option>
                        {% for pl in planning %}
                        <option value="{{pl.id}}">{{pl}}</option>
                        {% endfor %}
                     </select>
                  </div>
                  <div class="form-group">
                     <label>Full Name</label>
                     {% render_field form.full_name class="form-control" placeholder="Name and Lastname" id="full_name" %}
                  </div>
                  <div class="form-group">
                     <label>Email</label>
                     {% render_field form.email class="form-control" type="email" placeholder="Email" id="email" %}
                  </div>
                  <div class="form-group">
                     <label>Phone Number</label>
                     {% render_field form.phone class="form-control" placeholder="Phone Number" id="phone"%}
                  </div>
                  <div class="g-recaptcha" data-sitekey="6Lf6OrAaAAAAAPM9QDWZ4uJ6Aw7-sl5erQvboviA"></div>
                  <br>
                  <div class="form-group">
                     <input type="submit" value="Book now" class="ps-btn">
                  </div>
               </form>

FarisTours/templates/client/pattern.html
{% extends 'client/layout.html' %}


{% block title %}{% endblock title %}

{% block head %}


{% endblock head %}


{% block content %}







{% endblock content %}






{% block scripts %}

{% endblock scripts %}

FarisTours/templates/client/tour.html
{% extends 'client/layout.html' %}
{% load widget_tweaks %}
{% block title %}{% endblock title %}
{% block head %}
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
<script src="https://js.stripe.com/v3/"></script>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
{% include 'django_quill/media.html' %}
<style>
   .swiper-container {
   width: 100%;
   height: 100%;
   }
   .swiper-slide {
   text-align: center;
   font-size: 18px;
   background: #fff;
   /* Center slide text vertically */
   display: -webkit-box;
   display: -ms-flexbox;
   display: -webkit-flex;
   display: flex;
   -webkit-box-pack: center;
   -ms-flex-pack: center;
   -webkit-justify-content: center;
   justify-content: center;
   -webkit-box-align: center;
   -ms-flex-align: center;
   -webkit-align-items: center;
   align-items: center;
   }
   .swiper-slide img {
   display: block;
   width: 100%;
   height: 100%;
   object-fit: cover;
   }
</style>
<link
   rel="stylesheet"
   href="https://unpkg.com/swiper/swiper-bundle.min.css"/>
{% endblock head %}
{% block content %}




{% endblock content %}
{% block scripts %}
<script type="text/javascript">
   $.noConflict();
   jQuery(document).ready(function ($) {
       $('#CollectedDate').datepicker();
   });
</script>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<!-- Initialize Swiper -->
<script>
   var swiper = new Swiper(".mySwiper", {
     spaceBetween: 30,
     centeredSlides: true,
     autoplay: {
       delay: 3500,
       disableOnInteraction: false,
     },
     pagination: {
       el: ".swiper-pagination",
       clickable: true,
     },
     navigation: {
       nextEl: ".swiper-button-next",
       prevEl: ".swiper-button-prev",
     },
     
   });
</script>
<script>
   window.onload = function() {
     var recaptcha = document.forms["booking_form"]["g-recaptcha-response"];
     recaptcha.required = true;
     recaptcha.oninvalid = function(e) {
   	// do something
   	alert("Please complete the captcha");
     }
   }
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>
<script>
   var stripe = Stripe("{{STRIPE_PUBLIC_KEY}}");
   const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
   $("#booking_form").submit(function(e){
   	e.preventDefault();
   	$.ajax({
   		
              type: 'POST',
              url: "{% url 'ui:create-checkout-session' tour.slug %}",
              data: {
   			planning: $("#planning").val(),
   			full_name:$("#full_name").val() ,
   			email:$("#email").val(),
   			phone:$("#phone").val(),
   			csrfmiddlewaretoken: '{{ csrf_token }}',
   		},
              success: function (response) {
                  var id = response["id"];
   			return stripe.redirectToCheckout({ sessionId: id });
              },
              error: function (response) {
   			alter(response["error"]);
              }
          })
   })
</script>
{% endblock scripts %}

FarisTours/templates/client/tours.html
{% extends 'client/layout.html' %}
{% block title %}Tours{% endblock title %}
{% block head %}
{% endblock head %}
{% block content %}
<div class="ps-hero">
   <div class="container">
      <h3>SHOP PAGE</h3>
      <p>Shop with Sidebar</p>
   </div>
</div>
<main class="ps-main">
   <div class="ps-container">
      <div class="ps-product-group no-sidebar pt-40" data-item="4">
         <div class="ps-product-group__header">
            <div class="ps-filter">
               <div class="row">
                  <div class="col-lg-8 col-md-8 col-sm-6 col-xs-12 ">
                     <div class="ps-filter__trigger">
                        <div class="ps-filter__icon"><span></span></div>
                        <p>Filter Tour</p>
                     </div>
                  </div>
                  <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 ">
                     <div class="ps-filter__result">
                        <p>Showing 1–12 of 35 results</p>
                     </div>
                  </div>
               </div>
               <div class="ps-filter__content">
                  <div class="ps-filter__column" data-mh="column">
                     <h3>SORT CATEGORIES BY</h3>
                     <ul class="ps-list--filter">
                        <li class="current"><a href="product-listing.html">All</a></li>
                        <li><a href="product-listing.html">Men</a></li>
                        <li><a href="product-listing.html">Women</a></li>
                        <li><a href="product-listing.html">Suite & Jean</a></li>
                        <li><a href="product-listing.html">Accessories</a></li>
                        <li><a href="product-listing.html">Kids</a></li>
                        <li><a href="product-listing.html">Handmade</a></li>
                     </ul>
                  </div>
                  <div class="ps-filter__column" data-mh="column">
                     <h3>SORT PRODUCTS BY</h3>
                     <ul class="ps-list--filter">
                        <li class="current"><a href="product-listing.html">Default Sorting</a></li>
                        <li><a href="product-listing.html">Sort by popularity</a></li>
                        <li><a href="product-listing.html">Sort by average rating</a></li>
                        <li><a href="product-listing.html">Sort by newness</a></li>
                        <li><a href="product-listing.html">Sort by price: low to high</a></li>
                        <li><a href="product-listing.html">Sort by price: high to low</a></li>
                     </ul>
                  </div>
                  <div class="ps-filter__column" data-mh="column">
                     <h3>FILTER BY PRICE</h3>
                     <ul class="ps-list--filter">
                        <li class="current"><a href="product-listing.html">All</a></li>
                        <li><a href="product-listing.html">£10.00 - £110.00</a></li>
                        <li><a href="product-listing.html">£110.00 - £210.00</a></li>
                        <li><a href="product-listing.html">£210.00 - £310.00</a></li>
                        <li><a href="product-listing.html">£310.00+</a></li>
                     </ul>
                  </div>
                  <div class="ps-filter__column" data-mh="column">
                     <h3>FILTER BY PRICE</h3>
                     <ul class="ps-list--color">
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                     </ul>
                  </div>
                  <div class="ps-filter__column" data-mh="column">
                     <h3>FILTER BY PRICE</h3>
                     <ul class="ps-list--filter">
                        <li class="current"><a href="product-listing.html">All</a></li>
                        <li><a href="product-listing.html">New</a></li>
                        <li><a href="product-listing.html">SaleOff</a></li>
                        <li><a href="product-listing.html">Show Only Products On Sale</a></li>
                        <li><a href="product-listing.html">In Stock Only</a></li>
                        <li><a href="product-listing.html">Out of stock</a></li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
         <div class="ps-product-group__content">
            <div class="ps-product-group__action"></div>
            {% for tr in tours %} 
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 ">
               <div class="ps-post ps-post--home">
                  <div class="ps-post__thumbnail">
                     <div class="ps-post__posted"><span class="date">${{tr.price}}</span>
                     </div>
                     <a class="ps-post__overlay" href="{% url 'ui:tour' tr.slug %}">
                     </a><img class="lazy" src="{{tr.thumbnail.url}}" alt="">
                  </div>
                  <div class="ps-post__content">
                     <a class="ps-post__title" href="{% url 'ui:tour' tr.slug %}">{{tr.title}}</a>
                     <div class="br-wrapper br-theme-fontawesome-stars">
                        <div class="br-widget">
                {% for e in range %}
                               <a data-rating-value="{{e}}" data-rating-text="{{e}}" class="{% if e < tr.feedbacks %}br-selected br-current{% endif %}"></a>
                {% endfor %}
                        </div>
                     </div>
                     <p>Duration: {{tr.duration}} {% if tr.duration == 1 %} Day {% else %}Days{% endif %}</p>
                     <a class="ps-post__morelink" href="{% url 'ui:tour' tr.slug %}">View Tour<i class="ps-icon-arrow-right"></i></a>
                  </div>
               </div>
            </div>
            {% endfor %}
         </div>
         <div class="ps-product-group__footer">
            <div class="ps-pagination mb-50">
               <ul class="pagination">
                  <li><a href="#"><i class="fa fa-angle-left"></i></a></li>
                  <li class="active"><a href="#">1</a></li>
                  <li><a href="#">2</a></li>
                  <li><a href="#">3</a></li>
                  <li><a href="#">...</a></li>
                  <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
               </ul>
            </div>
         </div>
      </div>
   </div>
</main>
<div class="ps-section--partner">
   <div class="ps-container">
      <div class="owl-slider" data-owl-auto="true" data-owl-loop="true" data-owl-speed="5000" data-owl-gap="60" data-owl-nav="false" data-owl-dots="false" data-owl-item="5" data-owl-item-xs="3" data-owl-item-sm="3" data-owl-item-md="4" data-owl-item-lg="5" data-owl-duration="1000" data-owl-mousedrag="on"><a href="#"><img src="images/partner/1.png" alt=""></a><a href="#"><img src="images/partner/2.png" alt=""></a><a href="#"><img src="images/partner/3.png" alt=""></a><a href="#"><img src="images/partner/4.png" alt=""></a><a href="#"><img src="images/partner/5.png" alt=""></a><a href="#"><img src="images/partner/1.png" alt=""></a><a href="#"><img src="images/partner/2.png" alt=""></a><a href="#"><img src="images/partner/3.png" alt=""></a><a href="#"><img src="images/partner/4.png" alt=""></a><a href="#"><img src="images/partner/5.png" alt=""></a></div>
   </div>
</div>
<div class="ps-section--features">
   <div class="ps-container">
      <div class="row">
         <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 ">
            <div class="ps-iconbox">
               <header>
                  <i class="ps-icon-delivery-truck"></i>
                  <h3>FREE SHIPPING</h3>
                  <p>ON ORDER OVER $199</p>
               </header>
               <p>Want to track a package? Find tracking information and order details from Your Orders.</p>
            </div>
         </div>
         <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 ">
            <div class="ps-iconbox">
               <header>
                  <i class="ps-icon-money-1"></i>
                  <h3>100% MONEY BACK.</h3>
                  <p>WITHIN 30 DAYS AFTER DELIVERY.</p>
               </header>
               <p>You may return most new, unopened items sold within 30 days of delivery for a full refund.</p>
            </div>
         </div>
         <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 ">
            <div class="ps-iconbox">
               <header>
                  <i class="ps-icon-customer-service"></i>
                  <h3>SUPPORT 24/7.</h3>
                  <p>WE CAN HELP YOU ONLINE.</p>
               </header>
               <p>We offer a 24/7 customer hotline so you’re never alone if you have a question.</p>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock content %}
{% block scripts %}
{% endblock scripts %}