FarisTours/ui/urls.py
from django.urls import path
from . import views
from ui.views import CreateCheckoutSessionView

app_name = "ui"



urlpatterns = [
    path('',views.home,name="home"),
    path('tours',views.tours,name="tours"),
    path('stripe/webhooks',views.stripe_webhook,name="stripe_webhook"),
    path('success/',views.success,name="success"),
    path('cancel/',views.canceled,name="cancel"),
    path('create-checkout-session/<slug:slug>',views.CreateCheckoutSessionView,name="create-checkout-session"),
    path('tour/<slug:slug>',views.tour,name="tour"),
]

FarisTours/ui/models.py
from django.db import models

# Create your models here.

FarisTours/ui/forms.py
from django.forms import ModelForm 

from agent.models import BookingOrders, Payment

class BookingOrderForm(ModelForm):
    class Meta:
        model = BookingOrders
        fields = (
            'full_name',
            'email',
            'phone',
            
        )
    

FarisTours/ui/views.py
from django.shortcuts import render, redirect
from agent.models import Tour, TourDate, TourGallery, BookingOrders, Feedback
from .forms import BookingOrderForm
from django.conf import settings
from django.http import JsonResponse,HttpResponse
from django.views import View
import datetime, stripe
from django.core.paginator import Paginator

from django.views.decorators.csrf import csrf_exempt


stripe.api_key = settings.STRIPE_SECRET_KEY
STRIPE_WEBHOOk_KEY = "whsec_QqhNNdcJND2xLSfJucMySP3sr0hI6L11"


def home(request):
    top_tours = Tour.objects.filter(is_top=True)[:3]
    #this will dislay duplicated listing .. distinct method is working only with PostegresSQL
    #top_tours_gallery = TourGallery.objects.filter(tour__in=top_tours) #__in is usefull when you want to filter a lot of recors
    new_tours = Tour.objects.all().order_by('created_at')[:3][::-1] # [:3] means get last 3 record [::-1] used to reverse these records (des)
    #highly_rated_tours = Tour.objects.all().order_by('feedbacks')[:3] # get top last 3 record that currently have the highest feedback
    context = {
        'tours':top_tours,
        'new_tours':new_tours,
        #'highly_rated_tours':highly_rated_tours,
    }
    return render(request,"client/index.html",context)


def success(request):
    return render(request,"ui/success.html")

def canceled(request):
    return render(request,"ui/canceled.html")

def CreateCheckoutSessionView(request,slug):
    if request.is_ajax and request.method == "POST":
        tour = Tour.objects.get(slug=slug)
        DOMAIN_NAME = "{}://{}".format(request.scheme,request.get_host())
        full_name = request.POST.get('full_name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        planning_id=request.POST.get('planning')
        try:

            checkout_session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                line_items=[
                    {
                        'price_data': {
                            'currency': 'usd',
                            'unit_amount': tour.price * 100,
                            'product_data': {
                                'name': "Tour: {}".format(tour.title),
                                'images': ["{}://{}{}".format(request.scheme,request.get_host(),tour.thumbnail.url)], #get full url of that thumbnail
                            },
                        },
                        'quantity': 1,
                    },
                ],
                mode='payment',
                metadata = {
                    'planning_id':planning_id,
                    'full_name':full_name,
                    'email':email,
                    'phone':phone
                },
                success_url=DOMAIN_NAME + '/success/',
                cancel_url=DOMAIN_NAME + '/cancel/',
            )
            return JsonResponse({
                'id': checkout_session.id
            })
        except:
            return JsonResponse({
                'error': 'Please check your information and try again'
            })

now = datetime.datetime.now()
def tour(request,slug):
    tour = Tour.objects.get(slug=slug)
    galleries = TourGallery.objects.filter(tour=tour)
    planning = TourDate.objects.filter(tour=tour)
    feedbacks = Feedback.objects.filter(tour=tour)
    form = BookingOrderForm()
    if request.method == "POST":
        form = BookingOrderForm(request.POST or None)
        if form.is_valid():
            form.save()
        else:
            form = BookingOrderForm()
    context = {
        'tour':tour,
        'galleries':galleries,
        'form':form,
        'planning':planning,
        'STRIPE_PUBLIC_KEY': settings.STRIPE_PUBLIC_KEY,
        'range':range(5),
        'feedbacks':feedbacks

    }
    return render(request,"client/tour.html",context)

def tours(request):
    context = {
        'range':range(5), #feedback 
    }
    return render(request,"client/tours.html",context)
    

@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, STRIPE_WEBHOOk_KEY
    )
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)
    
    # Passed signature verification
    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']
        TourDate_instance = TourDate.objects.get(id=session["metadata"]["planning_id"])
        TourDate_instance.seats -= 1 
        TourDate_instance.save()
        form = BookingOrders(
                planning=TourDate_instance,
                full_name = session["metadata"]["full_name"],
                email = session["metadata"]["email"],
                phone = session["metadata"]["phone"],
                status = 'ok',
            )
        form.save()
        BookingOrder_instance = form.save()

    return HttpResponse(status=200)

FarisTours/templates/ui/canceled.html
Canceled!

FarisTours/templates/ui/home.html
{% extends 'ui/layout.html' %}

{% load static %}
{% block content %}


<section class="parallax_window_in" data-parallax="scroll" data-image-src="{% static 'ui/img/Faris.jpg' %}" data-natural-width="1400" data-natural-height="470">
		<div id="hero_video">
			<div id="animate_intro" class="animated fadeInUp">
				<h3>Enjoy a Perfect Tour</h3>
				<p>
					Find the best Tours and Excursion at the best price
				</p>
			</div>
		</div>
	</section>
<section class="wrapper">
		<div class="divider_border"></div>

		<div class="container">

			<div class="main_title">
				<h2>Our <span>Top</span> Travel Tours</h2>
				<p>Quisque at tortor a libero posuere laoreet vitae sed arcu. Curabitur consequat.</p>
			</div>
			<div class="row">
                {% for toptr in top_tours %}
				<div class="col-md-4 col-sm-6 wow fadeIn animated animated" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeIn;">
					<div class="img_wrapper">
						<div class="ribbon">
							<span>Popular</span>
						</div>
						<div class="price_grid">
							<sup>$</sup>{{toptr.price}}
						</div>
						<div class="img_container">
							<a href="{% url 'ui:single_tour' toptr.slug %}">
								<img src="{{toptr.thumbnail.url}}" width="800" height="533" class="img-responsive" alt="">
								<div class="short_info">
									<h3>{{toptr.title}}</h3>
									<em>Duration {{toptr.duration}} days</em>
									<p>
										{{toptr.subtitle}}
									</p>
									<div class="score_wp">Superb
										<div class="score">{{toptr.feedbacks}}</div>
									</div>
								</div>
							</a>
						</div>
					</div>
					<!-- End img_wrapper -->
				</div>
                {% endfor %}


			</div>
			<!-- End row -->

			<div class="main_title_2">
				<h3>View other <span>popular</span> tours</h3>
				<p>Quisque at tortor a libero posuere laoreet vitae sed arcu. Curabitur consequat.</p>
			</div>
			<div class="row list_tours">
				<div class="col-sm-6">
					<h3>New Tours</h3>
					<ul>
					{% for new_tour in new_tours %}
						<li>
							<div>
								<a href="{% url 'ui:single_tour' new_tour.slug %}">
									<figure><img src="{{new_tour.thumbnail.url}}" alt="thumb" class="img-rounded" width="60" height="60">
									</figure>
									<h4>{{new_tour.title}}</h4>
									<small>Duration {{new_tour.duration}} days</small>
									<span class="price_list">${{new_tour.price}}</span>
								</a>
							</div>
						</li>
					{% endfor %}
					</ul>
				</div>

				<div class="col-sm-6">
					<h3>Highly rated</h3>
					<ul>
						
					</ul>
				</div>

			</div>
			<!-- End row -->

			<p class="text-center add_bottom_45">
				<a href="{% url 'ui:tours' %}" class="btn_1">Explore all tours (24)</a>
			</p>

		</div>
	</section>
{% endblock content %}

FarisTours/templates/ui/layout.html
{% load static %}
<!DOCTYPE html>
<!--[if IE 9]><html class="ie ie9"><![endif]-->
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="FarisTours - Travel and Tours booking">
	<meta name="author" content="Ansonika">
	<title>FarisTours - The best Tours and Excursion at the best price</title>

	<!-- Favicons-->
	<link rel="shortcut icon" href="{% static 'ui/img/favicon.ico' %}" type="image/x-icon">
	<link rel="apple-touch-icon" type="image/x-icon" href="{% static 'ui/img/apple-touch-icon-57x57-precomposed.png' %}">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="{% static 'ui/img/apple-touch-icon-72x72-precomposed.png' %}">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="{% static 'ui/img/apple-touch-icon-114x114-precomposed.png' %}">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="{% static 'ui/img/apple-touch-icon-144x144-precomposed.png' %}">

	<!-- GOOGLE WEB FONT -->
	<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Satisfy" rel="stylesheet">

	<!-- BASE CSS -->
	<link href="{% static 'ui/css/animate.min.css' %}" rel="stylesheet">
	<link href="{% static 'ui/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'ui/css/style.css' %}" rel="stylesheet">
	<link href="{% static 'ui/css/responsive.css' %}" rel="stylesheet">
	<link href="{% static 'ui/css/menu.css' %}" rel="stylesheet">
	<link href="{% static 'ui/css/icon_fonts/css/all_icons.min.css' %}" rel="stylesheet">

	<!-- SPECIFIC CSS -->
	<link href="{% static 'ui/css/jquery.cookiebar.css' %}" rel="stylesheet">
    {% block specific_styles %}

	{% endblock specific_styles %}



	<!-- YOUR CUSTOM CSS -->
	<link href="{% static 'ui/css/custom.css' %}" rel="stylesheet">

	<!-- Modernizr -->
	<script src="{% static 'ui/js/modernizr.js' %}"></script>

	<!--[if lt IE 9]>
      <script src="js/html5shiv.min.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->

</head>

<body>

	<!--[if lte IE 8]>
        <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a>.</p>
    <![endif]-->

	<div class="layer"></div>
	<!-- Mobile menu overlay mask -->

	<div id="preloader">
		<div data-loader="circle-side"></div>
	</div>
	<!-- End Preload -->

	<!-- Header================================================== -->
	<div id="header_1">
		<header>
			<div id="top_line">
				<div class="container">				
					<div class="row">
						<div class="col-md-6 col-sm-6 col-xs-12">
							<a href="tel://212672793718" id="phone_top">+212 672 79 37 18</a><span id="opening">Mon - Sat 8.00/18.00</span>
						</div>
					</div>
					<!-- End row -->
				</div>
				<!-- End container-->
			</div>
			<!-- End top line-->

			<div class="container">
				<div class="row">
					<div class="col-md-3 col-sm-3 col-xs-3">
						<div id="logo_home">
							<h1><a href="/" title="City tours travel template">BesTours Travel&amp;Excursion Multipurpose Template</a></h1>
						</div>
					</div>
					<nav class="col-md-9 col-sm-9 col-xs-9">
						<ul id="tools_top">
							<li><a href="#" class="search-overlay-menu-btn"><i class="icon-search-6"></i></a>
							</li>
						</ul>
						<a class="cmn-toggle-switch cmn-toggle-switch__htx open_close" href="javascript:void(0);"><span>Menu mobile</span></a>
						<div class="main-menu">
							<div id="header_menu">
								<img src="{% static 'ui/img/logo_menu.png' %}" width="145" height="34" alt="Bestours" data-retina="true">
							</div>
							<a href="#" class="open_close" id="close_in"><i class="icon_set_1_icon-77"></i></a>
							<ul>
								<li>
									<a href="{% url 'ui:home' %}">Home</a>
									
								</li>
								<li>
									<a href="{% url 'ui:tours' %}">Tours</a>
									
								</li>
								<li>
									<a href="about.html">About us</a>
								</li>
								<li><a href="faq.html">Faq</a>
								</li>
								<li>
									<a href="contacts.html">Contact us</a>
								</li>
							</ul>
						</div>
						<!-- End main-menu -->
					</nav>
				</div>
			</div>
			<!-- container -->
		</header>
		<!-- End Header -->
	</div>
	<!-- End Header 1-->

		{% block content %}
		
		{% endblock content %}

	<footer>
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-sm-3">
					<h3>Contact the developer:</h3>
					<a href="tel://212672793718" id="phone">+212 672 79 37 18</a>
					<a href="mailto:contact@achraffaris.net" id="email_footer">contact@achraffaris.net</a>
				</div>
				<div class="col-md-2 col-sm-3">
					<h3>About</h3>
					<ul>
						<li><a href="#">About us</a>
						</li>
						<li><a href="#">FAQ</a>
						</li>
						<li><a href="#">Privacy Policy</a>
						</li>
						<li><a href="#">Terms and conditions</a>
						</li>
					</ul>
				</div>
				<div class="col-md-3 col-sm-12">
					<h3>Newsletter</h3>
					<div id="message-newsletter_2">
					</div>
					<form method="post" action="assets/newsletter.php" name="newsletter_2" id="newsletter_2">
						<div class="form-group">
							<input name="email_newsletter_2" id="email_newsletter_2" type="email" value="" placeholder="Your email" class="form-control">
						</div>
						<input type="submit" value="Subscribe" class="btn_1" id="submit-newsletter_2">
					</form>
				</div>
			</div>
			<!-- End row -->
			<hr>
			<div class="row">
				<div class="col-sm-8">
					<div class="styled-select">
						<select class="form-control" name="lang" id="lang">
							<option value="English" selected>English</option>
							<option value="French">French</option>
							<option value="Spanish">Spanish</option>
							<option value="Russian">Russian</option>
						</select>
					</div>
					<span id="copy">© FarisTours {% now "Y" %} - All rights reserved</span>
				</div>
				<div class="col-sm-4" id="social_footer">
					<ul>
						<li><a href="#"><i class="icon-facebook"></i></a>
						</li>
						<li><a href="#"><i class="icon-twitter"></i></a>
						</li>
						<li><a href="#"><i class="icon-google"></i></a>
						</li>
						<li><a href="#"><i class="icon-instagram"></i></a>
						</li>
					</ul>
				</div>
			</div>
			<!-- End row -->
		</div>
		<!-- End container -->
	</footer>
	<!-- End footer -->

	<div id="toTop"></div>
	<!-- Back to top button -->

	<!-- Search Menu -->
	<div class="search-overlay-menu">
		<span class="search-overlay-close"><i class="icon_close"></i></span>
		<form role="search" id="searchform" method="get">
			<input value="" name="q" type="search" placeholder="Search..." />
			<button type="submit"><i class="icon-search-6"></i>
			</button>
		</form>
	</div>
	<!-- End Search Menu -->

	<!-- COMMON SCRIPTS -->
    
	<script src="{% static 'ui/js/jquery-2.2.4.min.js' %}"></script>
	<script src="{% static 'ui/js/common_scripts_min.js' %}"></script>
	<script src="{% static 'ui/assets/validate.js' %}"></script>
	<script src="{% static 'ui/js/jquery.tweet.min.js' %}"></script>
	<script src="{% static 'ui/js/functions.js' %}"></script>

	<!-- SPECIFIC SCRIPTS -->
    {% block specific_scripts %}
    
    {% endblock specific_scripts %}

</body>

</html>

FarisTours/templates/ui/pattern.html
{% extends 'ui/layout.html' %}


{% block content %}

{% endblock content %}

FarisTours/templates/ui/single_tour.html
{% extends 'ui/layout.html' %}
{% load static %}

{% load widget_tweaks %}

{% block specific_styles %}
<link href="{% static 'ui/css/timeline.css' %}" rel="stylesheet">
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>

{% include 'django_quill/media.html' %}

{% endblock specific_styles %}


{% block content %}



<section class="parallax_window_in" data-parallax="scroll" data-image-src="" data-natural-width="1400" data-natural-height="470">
		<div id="sub_content_in">
			<div id="animate_intro" class="animated fadeInUp">
				<h1>{{tours.title}}</h1>
				<p>{{tours.subtitle}}</p>
			</div>
		</div>
	</section>


	<section class="wrapper">
		<div class="divider_border"></div>

		<div class="container">
			<div class="row">
				<div class="col-md-8">
					
					
					 <div class="owl-carousel add_bottom_15 owl-theme owl-responsive-1000 owl-loaded">
						<div class="owl-stage-outer">
						   <div class="owl-stage" style="transform: translate3d(0px, 0px, 0px); transition: all 0.25s ease 0s; width: 2250px;">
							  
							  {% for img in galleries %}
							  <div class="owl-item" style="width: 750px; margin-right: 0px;">
								<div class="item"><img src="{{img.image.url}}" alt="">
								</div>
							 </div>
							  {% endfor %}
								  
						   </div>
						</div>
						<div class="owl-controls">
						   <div class="owl-nav">
							  <div class="owl-prev" style="display: none;"></div>
							  <div class="owl-next" style="display: none;"></div>
						   </div>
						   <div class="owl-dots" style="">
							  <div class="owl-dot active"><span></span></div>
							  <div class="owl-dot"><span></span></div>
							  <div class="owl-dot"><span></span></div>
						   </div>
						</div>
					 </div>
					<ul class="nav nav-tabs">
						<li class="active"><a href="#tab_1" data-toggle="tab">Overview</a>
						</li>
						<li><a href="#tab_2" data-toggle="tab">Reviews</a>
						</li>
						<li><a href="#tab_3" data-toggle="tab">Map</a>
						</li>
					</ul>

					<div class="tab-content">
						<div class="tab-pane fade in active" id="tab_1">

							 {{tours.description.html |safe}}
							
						</div>
						<!-- End tab_1 -->

						<div class="tab-pane fade" id="tab_2">

							<div id="summary_review">
								<div class="review_score"><span>8,9</span>
								</div>
								<div class="review_score_2">
									<h4>Fabulous  <span>(Based on 34 reviews)</span></h4>
									<p>
										Vero consequat cotidieque ad eam. Ea duis errem qui, impedit blandit sed eu. Ius diam vivendo ne.
									</p>
								</div>
							</div>
							<!-- End review summary -->

							<div class="reviews-container">

								

							</div>
							<!-- End review-container -->

							<hr>

							<div class="add-review">
								<h4>Leave a Review</h4>
								<div id="message-review"></div>
								<form method="post" action="assets/review.php" id="review" autocomplete="off">
									<input type="hidden" id="tour_name_review" name="tour_name_review" value="General Louvre Tour">
									<div class="row">
										<div class="form-group col-md-6">
											<label>Name *</label>
											

											<input type="text" name="name_review" id="name_review" placeholder="" class="form-control">
										</div>
										<div class="form-group col-md-6">
											<label>Lastname *</label>
											<input type="text" name="lastname_review" id="lastname_review" placeholder="" class="form-control">
										</div>
										<div class="form-group col-md-6">
											<label>Email *</label>
											<input type="email" name="email_review" id="email_review" class="form-control">
										</div>
										<div class="form-group col-md-6">
											<label>Rating </label>
											<select name="rating_review" id="rating_review" class="form-control">
												<option value="">Select</option>
												<option value="1">1 (lowest)</option>
												<option value="2">2</option>
												<option value="3">3</option>
												<option value="4">4</option>
												<option value="5">5 (medium)</option>
												<option value="6">6</option>
												<option value="7">7</option>
												<option value="8">8</option>
												<option value="9">9</option>
												<option value="10">10 (highest)</option>
											</select>
										</div>
										<div class="form-group col-md-12">
											<label>Your Review</label>
											<textarea name="review_text" id="review_text" class="form-control" style="height:130px;"></textarea>
										</div>
										<div class="form-group col-md-6">
											<label>Are you human? 3 + 1 =</label>
											<input type="text" id="verify_review" class=" form-control" placeholder="Are you human? 3 + 1 =">
										</div>
										<div class="form-group col-md-12">
											<input type="submit" value="Submit" class="btn_1" id="submit-review">
										</div>
									</div>
								</form>
							</div>

						</div>
						<!-- End tab_2 -->

						<div class="tab-pane fade" id="tab_3">
							<div id="map"></div>
							<!-- end map-->

							<div class="box_map">
								<i class="icon_set_1_icon-25"></i>
								<h4>By Train/tube</h4>
								<p>Per cu esse assentior delicatissimi, qui adipiscing dissentiunt mediocritatem in, dicat voluptaria no eam. No est alia eloquentiam. Has rebum vulputate adversarium no. Pro cibo delenit scripserit id.</p>
							</div>


							<div class="box_map">
								<i class="icon_set_1_icon-26"></i>
								<h4>By bus</h4>
								<p>Per cu esse assentior delicatissimi, qui adipiscing dissentiunt mediocritatem in, dicat voluptaria no eam. No est alia eloquentiam. Has rebum vulputate adversarium no. Pro cibo delenit scripserit id.</p>
							</div>

							<div class="box_map">
								<i class="icon_set_1_icon-21"></i>
								<h4>By Taxi/cabs</h4>
								<p>Per cu esse assentior delicatissimi, qui adipiscing dissentiunt mediocritatem in, dicat voluptaria no eam. No est alia eloquentiam. Has rebum vulputate adversarium no. Pro cibo delenit scripserit id.</p>
							</div>

						</div>
						<!-- End tab_3 -->
					</div>
					<!-- End tabs -->
				</div>
				<!-- End Col -->



				<aside class="col-md-4">
					<div class="box_style_2">
<div class="price text-center bg-secondary">
							<strong class="text-success">${{tours.price}}</strong><small>per person</small>
						</div>						
						<div id="message-booking"><hr></div>
						<form method="post" id="booking_form" name="booking_form">
							{% csrf_token %}
							<div class="form-group">
								<label>When?</label>
									<select id="planning" class="form-control">
										<option value="">Select</option>
										
										{% for pl in planning %}
											<option value="{{pl.id}}">{{pl}}</option>
										{% endfor %}
											
									</select>
								</div>
							<div class="form-group">
								<label>Name and Lastname</label>
								{% render_field form.full_name class="form-control" placeholder="Name and Lastname" id="full_name" %}
							</div>
							<div class="form-group">
								<label>Email</label>
								{% render_field form.email class="form-control" type="email" placeholder="Email" id="email" %}
							</div>
							<div class="form-group">
								<label>Phone Number</label>
								{% render_field form.phone class="form-control" placeholder="Phone Number" id="phone"%}

							</div>
							<div class="g-recaptcha" data-sitekey="6LegG9kaAAAAAOOcuXk6PrVAwRuTc8hSo5OguRBG"></div>
							<br>
							<div class="form-group">
								<input type="submit" value="Book now" class="btn_full">
							</div>
							</form>        
						<hr>
						<a href="#0" class="btn_outline"> or Contact us</a>
						<a href="tel://004542344599" id="phone_2"><i class="icon_set_1_icon-91"></i>+45 423 445 99</a>

					</div>
				</aside>
			</div>
			<!-- End row -->
		</div>
		<!-- End container -->
	</section>
	<!-- End section -->


    {% block specific_scripts %}

	<script src="{% static 'ui/js/sidebar_carousel_detail_page_func.js' %}"></script>
	<script src="{% static 'ui/js/infobox.js' %}"></script>
	<script>
		window.onload = function() {
		  var recaptcha = document.forms["booking_form"]["g-recaptcha-response"];
		  recaptcha.required = true;
		  recaptcha.oninvalid = function(e) {
			// do something
			alert("Please complete the captcha");
		  }
		}
	</script>
    

 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>

 <script>
	var stripe = Stripe("{{STRIPE_PUBLIC_KEY}}");
	const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
	$("#booking_form").submit(function(e){
		e.preventDefault();
		$.ajax({
			
            type: 'POST',
            url: "{% url 'ui:create-checkout-session' tours.slug %}",
            data: {
				planning: $("#planning").val(),
				full_name:$("#full_name").val() ,
				email:$("#email").val(),
				phone:$("#phone").val(),
				csrfmiddlewaretoken: '{{ csrf_token }}',
			},
            success: function (response) {
                var id = response["id"];
				return stripe.redirectToCheckout({ sessionId: id });
            },
            error: function (response) {
				alter(response["error"]);
            }
        })
	})
</script>

    {% endblock specific_scripts %}







{% endblock content %}

FarisTours/templates/ui/success.html
Success!!